title: "Laura Payan Cepeda"
logo: "https://github.com/laurapayancepeda/portfolioo/raw/main/cropped_image%20(1).png"
description: "Passionate about turning data into strategy"
theme: "jekyll-theme-minimal"
