title: "Laura Payan Cepeda"
logo: "https://github.com/laurapayancepeda/portfolioo/blob/bf7c86eac7901a527bb4a33f159c378443e28c73/cropped_image%20(1).png"
description: "Passionate about turning data into strategy"
theme: "jekyll-theme-minimal"
